def normalize_model(json: str) -> str: ...
def preflight(json: str) -> str: ...
def inspect_mesh(
    stl: bytes, target: str, solid_volume_mm3: float, relative_tolerance: float
) -> str: ...
def export_allowed(json: str) -> bool: ...
