MAX_LOCATIONS: int

def normalize_model(json: str) -> str: ...
def preflight(json: str) -> str: ...
def evaluate_voxels(json: str) -> str: ...
def evaluate_snap_fits(json: str) -> str: ...
def evaluate_fastener_releases(json: str) -> str: ...
def evaluate_connectors(json: str) -> str: ...
def evaluate_stl_voxels(stl: bytes, target: str, policy: str, plan: str) -> str: ...
def voxel_sections(json: str, part: str, plan: str | None, planes: str) -> str: ...
def stl_sections(stl: bytes, policy: str, plan: str, planes: str) -> str: ...
def stl_triangles(stl: bytes) -> bytes: ...
def inspect_mesh(
    stl: bytes, target: str, solid_volume_mm3: float, relative_tolerance: float
) -> str: ...
def export_allowed(json: str) -> bool: ...
